Feature fifth milestone
RossielCS/ror-social-scaffold pull request #2
Opened 2020-06-22 22:28 UTC by RossielCS

## This PR addresses the addition fo the following features:
- 'Invite to friendship' next to the user name.
- The user can see a 'pending response' message next to the user name he requested a friendship.
- The user can accept or reject a friendship.
- View post shows the number of likes and comments.
- The timeline only shows the post of the user and his friends.
- Users have a profile image.
- Added a profile section for the current user.
Also has:

- Unit and Integration testings

2020-06-23 00:51 UTC, majovanilla requested changes
Hey @RossielCS , 👋

## You did a *great* job on this project! 💜 

Your app has almost everything it was required for this milestone and it's working just fine.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

- Please check the comments I left on the code and make the necessary changes.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-06-23 00:51 UTC, majovanilla commented on app/views/layouts/application.html.erb
> +        </div>
You should add a menu to check for the received and sent invitations. Currently, you have that on the All Users menu, but it's not the best place to put it (I didn't find them easily). You can call it Notifications.

**Optional** You can make use of the friendship model and add an icon to show the number of friendship requests a user has, next to the menu title.

2020-06-23 00:51 UTC, majovanilla commented on app/views/users/show.html.erb
> +  <% end %>
- A user shouldn't be able to see another user's post unless they are friends. Right now that works great in the Timeline menu, but when you click on a user's profile link, is not working. Please fix that.

2020-06-24 05:00 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @RossielCS :lollipop: 

### Thank you for working on the changes requested by the previous reviewer :medal_sports: your project is very intuitive and I personally like the Friendship notification counter and the gravatar you've given to the user's profile that alone makes your project stand out from the rest :star2: :muscle:  There are still some things to work on :construction: :construction_worker_woman: 

#### Section specific

- [x] Please work with Git Flow: production `master` branch + main `development` branch + Pull Requests from feature branches to the `develop` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/git_flow_requirement.png) from Pathwright)

- I'm sorry this wasn't pointed out by the previous reviewer but your pull request should try to push changes into the branch Development from your feature-fifth-milestone instead of directly to the master, so please make the changes and create a correct Git Flow pull request.

#### Views & Helpers

* [x] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb). There should be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- I've put comments in your code where this rule wasn't respected so please remove all logic from views.

### That's it! :raised_hands: 

### Please :pray: do the changes :woman_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-06-24 05:00 UTC, euqueme commented on app/views/layouts/application.html.erb
>        <% else %>
- [x] Put the if/else statement in a helper method and render the links and/or markup within the helper instead of having this logic in the view

2020-06-24 05:00 UTC, euqueme commented on app/views/users/_friendship_button.html.erb
> +<% end %>
- [x] Put the if/else statement in a helper method and render the links, buttons and/or markup within the helper instead of having this logic in the view

2020-06-24 05:00 UTC, euqueme commented on app/views/users/show.html.erb
> +  <% end %>
- [x] Put the if/else statement in a helper method and render the links and/or markup within the helper instead of having this logic in the view

2020-06-24 05:00 UTC, euqueme commented on app/views/users/show.html.erb
> +    <% end %>
- [x] Put the if/else statement in a helper method and render the links and/or markup within the helper instead of having this logic in the view

2020-06-24 05:00 UTC, euqueme commented on app/views/users/user_notifications.html.erb
> +<% end %>
- [x] Put the if/else statement in a helper method and render the links and/or markup within the helper instead of having this logic in the view

2020-06-24 05:00 UTC, euqueme commented on app/views/users/user_notifications.html.erb
> +  <% end %>
- [x] Put the if/else statement in a helper method and render the links and/or markup (if you have several lines of markup to render you can also use partials to help you achieve this) within the helper instead of having this logic in the view

2020-06-25 00:03 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello @RossielCS ,  You have done a great job with this project. :clap:

#### You can go ahead and merge !!!

2020-06-25 00:51 UTC, merged